project:
  type: website
  output-dir: docs

website:
  title: "Mat4Jordi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Research
        menu:
        - href: research/research-lines.qmd
          text: Research Lines
        - href: research/thesis.qmd
          text: Thesis

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



